#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
# Add reverse history search
bindkey '^R' history-incremental-search-backward
bindkey '^?' backward-delete-char

MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"

export FIGNORE=CVS:\~:.o:.svn
export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)
export GROOVY_HOME=/usr/local/opt/groovy/libexec
export GRADLE_HOME=/usr/local/opt/gradle/libexec
export PYTHON_HOME=/usr/local/share/python
export M2_HOME=/usr/local/opt/maven/libexec
export M2=$M2_HOME/bin
#export SCALA_HOME=/usr/local/opt/scala/libexec
export MAVEN_OPTS="-Xmx1g"
export LESS="FRrXei"
export PDSH_RCMD_TYPE=ssh

# Uncomment the next part when I work with nvm
#export NVM_DIR="$HOME/.nvm"
#. "$(brew --prefix nvm)/nvm.sh"

cdpath=(
  ~/sandbox/userstore/
  ~/sandbox/identity/
  ~/sandbox
  ~/my_data/
  ~
)

export EDITOR=/usr/local/bin/vim
export ANDROID_HOME=/usr/local/opt/android-sdk
path=(
  $path
  #$HOME/.rvm/bin
  #$HOME/devtools/cassandra/bin
  $HOME/.appreciatekit/bin
  $HOME/.scalaenv/bin
)

# Paths for Go
export GOPATH=$HOME/gopath
#export GO15VENDOREXPERIMENT=1

alias gru="git remote update -p"
alias hideme='history -d $((HISTCMD-1))'
alias hideprev='history -d $((HISTCMD-2)) && history -d $((HISTCMD-1))'
alias lintian="lintian --color=auto"
alias locate="mdfind -name"
alias mc="mvn clean"
alias mci="mvn clean install"
alias mcp="mvn clean package"
alias mp="mvn package"
alias mvni="mvn install -Dmaven.test.skip"
alias ports='sudo lsof -iTCP -sTCP:LISTEN -n -P'
alias rm='nocorrect rm'
#
# this is for the cool dotfiles management
alias cfg='GIT_DIR=$HOME/.cfg GIT_WORK_TREE=$HOME git'

eval "$(hub alias -s)"
GITHUB_USER=Oakie3CR

#Eject command for volumes
eject () {
/usr/sbin/diskutil eject $1
}

# I like applications in /Applications
export HOMEBREW_CASK_OPTS="--appdir=/Applications"

#eval "$(pyenv virtualenv-init -)"

# This OC Tanner specific environment variables
OCT_USER=christian.rigdon
OCT_PASS=AKCp2WXCNFMht5btsQKphdDEHde4cakCs73gYFK3kSXkys5rur8xENpwbevtNfXG2xf2ch2pR
export OCT_ARTIFACTORY_USER=$OCT_USER
export OCT_ARTIFACTORY_PASS=$OCT_PASS
export OCT_VAULT_SHARED_READ_ARTIFACTORY_USERNAME=$OCT_USER
export OCT_VAULT_SHARED_READ_ARTIFACTORY_PASSWORD=$OCT_PASS
export TOKEN_URL=https://vision-dev.appreciatehub.com/api/login/token
export AVATAR_ORIGINAL_URI=https://s3.amazonaws.com/oc-images-api/test/users/avatars/default/original.png
export AVATAR_PROFILE_URI=https://s3.amazonaws.com/oc-images-api/test/users/avatars/default/profile.png
export AVATAR_THUMB_URI=https://s3.amazonaws.com/oc-images-api/test/users/avatars/default/thumb.png
export VISION_URL=https://vision-qa.appreciatehub.com
export EVENTS_SERVER_URL=https://eventsapi-pfm-qa.alamoappi.octanner.io
export MEMCACHED_URL=oct-68ddf2a5.fuetsj.0001.usw2.cache.amazonaws.com:6379

unsetopt auto_name_dirs

source ~/.brew-token

eval "$(scalaenv init -)"

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
