#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
# Add reverse history search
bindkey '^R' history-incremental-search-backward
bindkey '^?' backward-delete-char

MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"

export FIGNORE=CVS:\~:.o:.svn
export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)
export GROOVY_HOME=/usr/local/opt/groovy/libexec
export GRADLE_HOME=/usr/local/opt/gradle/libexec
export PYTHON_HOME=/usr/local/share/python
export M2_HOME=/usr/local/opt/maven/libexec
export M2=$M2_HOME/bin
export SCALA_HOME=/usr/local/opt/scala/libexec
#export JBOSS_HOME=/opt/jboss
export MAVEN_OPTS="-Xmx1g"
export LESS="FRXei"
export PDSH_RCMD_TYPE=ssh
cdpath=(. ~/sandbox/alianza/ax ~/sandbox/alianza/common ~/sandbox/alianza/core/ ~/sandbox/alianza/environments/
~/sandbox/alianza/microservices/ ~/sandbox/alianza/docker ~/sandbox/alianza/call_routing ~/sandbox/alianza/github/
~/sandbox/alianza/voicemail/ ~/sandbox/alianza/ ~/sandbox/ ~)
export EDITOR=/usr/local/bin/vim
#export FORGE_HOME=~/devtools/forge-distribution-1.0.4.Final
export ANDROID_HOME=/usr/local/opt/android-sdk

# Paths for Go
export GOPATH=$HOME/gopath
#export GO15VENDOREXPERIMENT=1

# Export for alianza scripts
export ALIANZA_HOME="$HOME/sandbox/alianza"

alias gru="git remote update -p"
alias hideme='history -d $((HISTCMD-1))'
alias hideprev='history -d $((HISTCMD-2)) && history -d $((HISTCMD-1))'
alias lintian="lintian --color=auto"
alias locate="mdfind -name"
alias mc="mvn clean"
alias mci="mvn clean install"
alias mcp="mvn clean package"
alias mp="mvn package"
alias mvni="mvn install -Dmaven.test.skip"
alias ports='sudo lsof -iTCP -sTCP:LISTEN -n -P'
#
# this is for the cool dotfiles management
alias cfg='GIT_DIR=$HOME/.cfg GIT_WORK_TREE=$HOME git'

#eval "$(hub alias -s)"
GITHUB_USER=Oakie3CR

# I like applications in /Applications
export HOMEBREW_CASK_OPTS="--appdir=/Applications"

unsetopt auto_name_dirs
export PATH="$PATH:$HOME/.rvm/bin"

source ~/.brew-token


test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# Enable iterm3 shell integration
source ~/.iterm2_shell_integration.`basename $SHELL`
